### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by arthurvr** [dharmeshkakadia/awesome-mesos#10]
> https://github.com/nicostratus/mesos-services 

This link seems broken ^

**Comment by arthurvr** [comment]
Something defunct is better just removed. This way it doesn't add any value.

**Comment by dharmeshkakadia** [comment]
I thought defunct was better because it keeps the authors "historic contribution" without confusing people. May be if we get too many of these "defuncts", we can move it to different section or remove it at that point. However, looking at the current pace of Mesos, it's unlikely. Thoughts?
