### ISSUE TITLE
Please add Satyr and dask.mesos

### ISSUE THREAD

**Issue by kszucs** [dharmeshkakadia/awesome-mesos#19]
- https://github.com/lensacom/satyr
- https://github.com/lensacom/dask.mesos

**Comment by dharmeshkakadia** [comment]
Great to learn about those projects ! Please add them to the appropriate sections and open a Pull Request. Community contributions are always welcome !

**Comment by dharmeshkakadia** [comment]
Added in 2ddf74c789c57cc940d3a9a34948d50a82c5ad6f.
